# This is a basic workflow that is manually triggered

name: Hola mundo

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Mi-primer-job:
    name: Mi primer job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Imprimir
      env:
        MI_VARIABLE: Hola mundo
      run:  echo #$MI_VARIABLE.
      
  Mi-segundo-job:
    needs: Mi-primer-job
    name: Mi segundo job
    runs-on: ubuntu-latest
    steps:
    - name: Imprimir
      id: imprimir
      run: echo ${{needs.Mi-primer-job.outputs.salida}}
